asdf-community/infrastructure

terraform/github/collaborators.tf
terraform/github/repositories.tf
terraform/github/teams.tf

https://github.com/TomWright/dasel

feat(dasel): ✨  add dasel

---

terraform/github/repositories.tf
terraform/github/teams.tf

feat: ✨  add kubebuilder

---

terraform/github/repositories.tf
terraform/github/teams.tf

feat: ✨  add asdf-svu plugin repo

---

terraform/github/teams.tf

Add jfly to asdf-direnv team

---

terraform/github/repositories.tf

@asdf-community/asdf-quarkus Once you have moved the repository, please comment here. I will merge this and import the repository into Terraform appropriately.

Import asdf-quarkus repository

---

terraform/github/repositories.tf

@asdf-community/asdf-python Once you have moved the repository, please comment here. I will merge this and import the repository into Terraform appropriately.

Import asdf-python repository

---

terraform/github/repositories.tf

@asdf-community/asdf-helmsman Once you have moved the repository, please comment here. I will merge this and import the repository into Terraform appropriately.

Import asdf-helmsman repository

---

terraform/github/repositories.tf

@asdf-community/asdf-pdm Once you have moved the repository, please comment here. I will merge this and import the repository into Terraform appropriately.

Import asdf-pdm repository

---

terraform/github/repositories.tf
terraform/github/teams.tf

@asdf-community/asdf-go Once you have moved the repository, please comment here. I will merge this and import the repository into Terraform appropriately.

Import asdf-go repository

---

terraform/github/repositories.tf

Closes https://github.com/asdf-vm/asdf-plugins/issues/850

Enable `has_discussions`

---

terraform/github/teams.tf

Following the instructions kindly provided by @smorimoto [here](https://github.com/orgs/asdf-community/discussions/57#discussioncomment-6430545)

Add asdf-kiota team

---

terraform/github/repositories.tf

This is a smooth process, thanks a lot for the support again @smorimoto

Import asdf-kiota repository

---

terraform/github/teams.tf

As discussed in [1], I'm just going through the process of moving `asdf-odo` [2] into this community organization.
Please do let me know if there is anything else to change in this PR.
Thank you!
[1] https://github.com/orgs/asdf-community/discussions/43
[2] https://github.com/rm3l/asdf-odo

Add `asdf-odo` team

---

terraform/github/repositories.tf

Add asdf-duckdb repo

---

terraform/github/teams.tf

Adds @mindovermiles262 as a maintainer (creator) for asdf-dapr-cli and asdf-kp (kpack)

feat: added asdf dapr cli and asdf kpack

---

terraform/github/teams.tf

Adds `asdf-scala-cli` from @rlemaitre

feat: Add asdf-scala-cli in teams.tf

---

terraform/github/repositories.tf
terraform/github/teams.tf

Add asdf-scala-cli to repositories according to the [guidelines](https://github.com/asdf-community/.github/blob/master/GUIDELINES.md)

feat: Add asdf-scala-cli to repositories

---

terraform/github/teams.tf

https://github.com/osdiab/asdf-intlc

add asdf-intlc to teams

---

terraform/github/teams.tf

add `asdf-mimirtool` to `asdf-community`.

feat(teams): add asdf-mimirtool

---

terraform/github/teams.tf

Adding the `asdf-temporal` plugin to `asdf-community`.

feat(teams): add asdf-temporal

---

terraform/github/repositories.tf

Manage asdf-mimirtool by Terraform.

feat(repositories): add asdf-mimirtool management

---

terraform/github/repositories.tf
terraform/github/teams.tf

feat(teams): add asdf-promtool

---

terraform/github/teams.tf

Add @hariscodes to @asdf-community/asdf-temporal

chore: add member to asdf-temporal

---

terraform/github/teams.tf

Add user `hqnna` as a maintainer of `asdf-swift`

feat(teams): add `asdf-swift` maintainers

---

terraform/github/repositories.tf

Reverts asdf-community/infrastructure#109

Revert "Add Pomerium-CLI Plugin"

---

terraform/github/repositories.tf

Added asdf-pomerium-cli repo to infra-as-code

Add Pomerium-CLI Repo

---

terraform/github/teams.tf

Hi!
I'd like to add an asdf plugin for [moonrepo](https://moonrepo.dev/) to asdf-community. Adding my name to the teams file, per the docs.

Add asdf-moon to teams.tf

---

terraform/github/repositories.tf
terraform/github/teams.tf

Additionally, add particledecay as a maintainer of the respective repos.
There will be additional plugins added as they are updated soon.

feat: add etcd, kconf, lab, and task plugins

---

terraform/github/repositories.tf

Add the moonrepo plugin to the repos terraform file.

Add moonrepo to repositories.tf

---

terraform/github/teams.tf

I'm following [these guidelines](https://github.com/asdf-community/.github/blob/master/GUIDELINES.md) to move the following repositories to the organization:
- [asdf-tuist](https://github.com/tuist/asdf-tuist)
- [asdf-tuist-cloud](https://github.com/tuist/asdf-tuist-cloud)
Please, let me know if you need additional information regarding the project.

Include `asdf-tuist` and `asdf-tuist-cloud` repositories

---

terraform/github/teams.tf

A part of https://github.com/orgs/asdf-community/discussions/56

Add asdf-flutter team

---

terraform/github/teams.tf

Add asdf-krelay

---

terraform/github/repositories.tf

krelay repository

---

terraform/github/teams.tf

Plugin I intend to transfer: https://github.com/vthiery/asdf-stratus-red-team

feat(teams): add stratus-red-team

---

terraform/github/teams.tf

Add team for the plugin [asdf-cloak-swift](https://github.com/lordcodes/asdf-cloak-swift).

feat(teams): Add asdf-cloak-swift team

---

terraform/github/teams.tf

Add team for the plugin [asdf-swifthooks](https://github.com/lordcodes/asdf-swifthooks).

feat(teams): Add asdf-swifthooks team

---

terraform/github/repositories.tf

close https://github.com/orgs/asdf-community/discussions/56

Import asdf-flutter repository

---

terraform/github/repositories.tf

Adds [asdf-swifthooks](https://github.com/asdf-community/asdf-swifthooks) repo to infrastructure.

Add asdf-swifthooks

---

terraform/github/repositories.tf

Terraform https://github.com/asdf-community/asdf-stratus-red-team repository.

feat: add asdf-stratus-red-team

---

terraform/github/repositories.tf

Adds [asdf-cloak-swift](https://github.com/asdf-community/asdf-cloak-swift) repo to infrastructure.

Add asdf-cloak-swift

---

terraform/github/teams.tf

Add asdf-tomcat
